from __future__ import annotations

from .client import LLMClient, get_llm_client

SYSTEM_PROMPT = """You are a senior AML compliance officer and FinCEN SAR specialist.
You write Suspicious Activity Reports (SARs) that are:
- Factual, concise, and legally defensible
- Structured per FinCEN SAR form (5318g)
- Free of speculation — based only on provided transaction data
- Written in past tense, third person
- 150-250 words

Do NOT include placeholder text or [brackets]. Write the final narrative directly."""


def _build_user_prompt(
    typology: str,
    total_amount: float,
    n_transactions: int,
    subjects: list[dict],
    activity_start: str,
    activity_end: str,
    avg_score: float,
    universe_id: str,
) -> str:
    subject_lines = "\n".join(
        f"  - Account {s['account_id']} ({s['role']}): "
        f"{s['transaction_count']} txns, ${s['total_amount']:,.2f}, countries: {s.get('countries', [])}"
        for s in subjects[:5]
    )
    return f"""Write a SAR narrative for the following suspicious activity:

Typology: {typology.replace("_", " ").title()}
Activity Period: {activity_start} to {activity_end}
Total Suspicious Amount: ${total_amount:,.2f} USD
Number of Transactions: {n_transactions}
Average Alert Score: {avg_score:.2f}
Detection System: AML Multiverse Simulator ({universe_id})

Subjects involved:
{subject_lines}

Write a complete SAR narrative section suitable for FinCEN submission.
Focus on the specific typology pattern and the financial activity observed."""


class LLMSARWriter:
    """Replaces template-based SAR narratives with LLM-generated text."""

    def __init__(self, client: LLMClient | None = None) -> None:
        self.client = client or get_llm_client()

    def write_narrative(
        self,
        typology: str,
        total_amount: float,
        n_transactions: int,
        subjects: list[dict],
        activity_start: str,
        activity_end: str,
        avg_score: float,
        universe_id: str,
    ) -> str:
        user = _build_user_prompt(
            typology=typology,
            total_amount=total_amount,
            n_transactions=n_transactions,
            subjects=subjects,
            activity_start=activity_start,
            activity_end=activity_end,
            avg_score=avg_score,
            universe_id=universe_id,
        )
        narrative = self.client.complete(SYSTEM_PROMPT, user)
        mode_tag = "" if self.client.is_real_llm else "\n[Generated by heuristic engine — set OPENAI_API_KEY for LLM quality]"
        return narrative + mode_tag
